Repository SuffolkLITLab/docassemble-MAVirtualCourt, pull requests merged in 2020-07, with the labels that each got.

#456 Add ability to skip pre-filled answers
  docassemble/MAVirtualCourt/data/questions/209a-filler.yml
Labels: test process

#468 Enhancements to interview
  docassemble/MAVirtualCourt/data/questions/Civil_Action_Cover_Sheet.yml
Labels: enhancement

#505 Adds the generic email button in to the download screen
  docassemble/MAVirtualCourt/data/questions/209a_package.yml
Labels: enhancement

#533 Improved directions
  docassemble/MAVirtualCourt/data/questions/motion-for-impoundment.yml
Labels: language fix
